stages:
  - dev
  - pre-build
  - build
  - deploy

variables:
  REGISTRY: ${CI_REGISTRY}/alifuz/backend/service-merchant-laravel
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  PHP_IMAGE: $CI_REGISTRY/images/php:8.0-fpm-infra

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

Composer Install:
  stage: dev
  image: $PHP_IMAGE
  script:
    - git config --global gitlab.accesstoken $CI_JOB_TOKEN
    - composer config gitlab-domains $CI_SERVER_HOST
    - composer config gitlab-token.$CI_SERVER_HOST $CI_JOB_TOKEN
    - composer i
  artifacts:
    paths:
      - vendor
    expire_in: 1 day
  tags:
    - docker
    - cicd

Test:
  stage: pre-build
  image: docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --no-cache --pull -f cicd/php-cli/Dockerfile -t $CI_REGISTRY_IMAGE:dev .
    - docker run --rm $CI_REGISTRY_IMAGE:dev ls -la
    - docker run --rm $CI_REGISTRY_IMAGE:dev ./vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots --config=./docker/config/.php-cs-fixer.php --allow-risky=yes
    - docker run --rm $CI_REGISTRY_IMAGE:dev ./vendor/bin/phpstan analyse --memory-limit=2G --configuration='docker/config/phpstan.neon.dist'
    - docker run --rm $CI_REGISTRY_IMAGE:dev ./vendor/bin/phpunit
  tags:
    - cicd
    - dind

build:
  stage: build
  only:
    - branches
  image: docker:dind
  services:
    - docker:20.10-dind
  before_script:
    - apk add --no-cache make
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - make build
    - if [ "${CI_COMMIT_REF_SLUG}" == "master" || "${CI_COMMIT_REF_SLUG}" == "stage"]; then make push; fi
  tags:
    - cicd
    - dind
